import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Layout from "@/components/DashboardLayout";
import { createClient } from "@/lib/supabase/server";
import { User } from "@/types";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TypeNext ⚡",
  description: "Generated by create next app",
  openGraph: {
    images: [
      "https://res.cloudinary.com/dm3qlqunj/image/upload/v1737388869/Group_174_1_jqjnol.png",
    ],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { user } = (await supabase.auth.getUser()).data;
  const { data } = await supabase
    .from("users")
    .select("*")
    .eq("id", user?.id)
    .single();

  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />

        <ThemeProvider attribute='class' defaultTheme='dark'>
          <Layout currentUser={data as unknown as User}>{children}</Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
